services:
  frontend:
    image: node:23-slim
    container_name: vite-dev
    working_dir: /app
    volumes:
      - ./:/app             # mount toàn bộ project
      - /app/node_modules   # tạo volume riêng cho node_modules
    ports:
      - "5173:5173"         # cổng mặc định của Vite dev server
    command: sh -c "npm install && npm run dev"
