FROM node:24.2-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./

ENV ENV="production"

RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && \
    npm ci

COPY . .

RUN npm run build

FROM nginxinc/nginx-unprivileged:1.27.5-alpine

COPY --from=builder usr/src/app/dist/ /usr/share/nginx/html

EXPOSE 8080

